<a href="https://colab.research.google.com/github/diggijo/OFI_Features/blob/main/OFI_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries

In [84]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [85]:
# Read the data
df = pd.read_csv("first_25000_rows.csv")

In [86]:
# Display the first few rows of the dataset
df.head()

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,depth,price,size,...,ask_sz_08,bid_ct_08,ask_ct_08,bid_px_09,ask_px_09,bid_sz_09,ask_sz_09,bid_ct_09,ask_ct_09,symbol
0,2024-10-21T11:54:29.221230963Z,2024-10-21T11:54:29.221064336Z,10,2,38,C,B,1,233.62,2,...,155,1,7,233.25,234.13,55,400,2,1,AAPL
1,2024-10-21T11:54:29.223936626Z,2024-10-21T11:54:29.223769812Z,10,2,38,A,B,0,233.67,2,...,155,1,7,233.25,234.13,55,400,2,1,AAPL
2,2024-10-21T11:54:29.225196809Z,2024-10-21T11:54:29.225030400Z,10,2,38,A,B,0,233.67,3,...,155,1,7,233.25,234.13,55,400,2,1,AAPL
3,2024-10-21T11:54:29.712600612Z,2024-10-21T11:54:29.712434212Z,10,2,38,A,B,2,233.52,200,...,155,1,7,233.25,234.13,55,400,2,1,AAPL
4,2024-10-21T11:54:29.764839221Z,2024-10-21T11:54:29.764673165Z,10,2,38,C,B,2,233.52,200,...,155,1,7,233.25,234.13,55,400,2,1,AAPL

In [ ]:
# Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 74 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ts_recv        5000 non-null   object
 1   ts_event       5000 non-null   object
 2   rtype          5000 non-null   int64
 3   publisher_id   5000 non-null   int64
 4   instrument_id  5000 non-null   int64
 5   action         5000 non-null   object
 6   side           5000 non-null   object
 7   depth          5000 non-null   int64
 8   price          5000 non-null   float64
 9   size           5000 non-null   int64
 10  flags          5000 non-null   int64
 11  ts_in_delta    5000 non-null   int64
 12  sequence       5000 non-null   int64
 13  bid_px_00      5000 non-null   float64
 14  ask_px_00      5000 non-null   float64
 15  bid_sz_00      5000 non-null   int64
 16  ask_sz_00      5000 non-null   int64
 17  bid_ct_00      5000 non-null   int64
 18  ask_ct_00      5000 non-null   int64
 19  bid_px_01      5000 non-null   float64
 20  ask_px_01      5000 non-null   float64
 21  bid_sz_01      5000 non-null   int64
 22  ask_sz_01      5000 non-null   int64
 23  bid_ct_01      5000 non-null   int64
 24  ask_ct_01      5000 non-null   int64
 25  bid_px_02      5000 non-null   float64
 26  ask_px_02      5000 non-null   float64
 27  bid_sz_02      5000 non-null   int64
 28  ask_sz_02      5000 non-null   int64
 29  bid_ct_02      5000 non-null   int64
 30  ask_ct_02      5000 non-null   int64
 31  bid_px_03      5000 non-null   float64
 32  ask_px_03      5000 non-null   float64
 33  bid_sz_03      5000 non-null   int64
 34  ask_sz_03      5000 non-null   int64
 35  bid_ct_03      5000 non-null   int64
 36  ask_ct_03      5000 non-null   int64
 37  bid_px_04      5000 non-null   float64
 38  ask_px_04      5000 non-null   float64
 39  bid_sz_04      5000 non-null   int64
 40  ask_sz_04      5000 non-null   int64
 41  bid_ct_04      5000 non-null   int64
 42  ask_ct_04      5000 non-null   int64
 43  bid_px_05      5000 non-null   float64
 44  ask_px_05      5000 non-null   float64
 45  bid_sz_05      5000 non-null   int64
 46  ask_sz_05      5000 non-null   int64
 47  bid_ct_05      5000 non-null   int64
 48  ask_ct_05      5000 non-null   int64
 49  bid_px_06      5000 non-null   float64
 50  ask_px_06      5000 non-null   float64
 51  bid_sz_06      5000 non-null   int64
 52  ask_sz_06      5000 non-null   int64
 53  bid_ct_06      5000 non-null   int64
 54  ask_ct_06      5000 non-null   int64
 55  bid_px_07      5000 non-null   float64
 56  ask_px_07      5000 non-null   float64
 57  bid_sz_07      5000 non-null   int64
 58  ask_sz_07      5000 non-null   int64
 59  bid_ct_07      5000 non-null   int64
 60  ask_ct_07      5000 non-null   int64
 61  bid_px_08      5000 non-null   float64
 62  ask_px_08      5000 non-null   float64
 63  bid_sz_08      5000 non-null   int64
 64  ask_sz_08      5000 non-null   int64
 65  bid_ct_08      5000 non-null   int64
 66  ask_ct_08      5000 non-null   int64
 67  bid_px_09      5000 non-null   float64
 68  ask_px_09      5000 non-null   float64
 69  bid_sz_09      5000 non-null   int64
 70  ask_sz_09      5000 non-null   int64
 71  bid_ct_09      5000 non-null   int64
 72  ask_ct_09      5000 non-null   int64
 73  symbol         5000 non-null   object
dtypes: float64(21), int64(48), object(5)
memory usage: 2.8+ MB

In [ ]:
# Get summary statistics for numerical columns
df.describe()

,rtype,publisher_id,instrument_id,depth,price,size,flags,ts_in_delta,sequence,bid_px_00,...,bid_sz_08,ask_sz_08,bid_ct_08,ask_ct_08,bid_px_09,ask_px_09,bid_sz_09,ask_sz_09,bid_ct_09,ask_ct_09
count,5000.0,5000.0,5000.0,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5.000000e+03,5000.000000,...,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,10.0,2.0,38.0,1.407600,233.806564,153.169200,128.031600,1.707528e+05,1.344078e+07,233.755936,...,89.929600,259.928600,1.38500,1.886200,233.364424,234.464900,68.382200,185.662200,1.434200,2.097200
std,0.0,0.0,0.0,1.455158,0.170972,129.459973,15.802283,5.433114e+04,1.254097e+06,0.112182,...,135.718278,450.030627,0.50242,1.341943,0.076242,0.232418,89.704575,344.015312,0.504104,1.460198
min,10.0,2.0,38.0,0.000000,232.600000,1.000000,0.000000,1.655530e+05,1.140585e+07,233.500000,...,1.000000,1.000000,1.00000,1.000000,233.200000,233.680000,1.000000,1.000000,1.000000,1.000000
25%,10.0,2.0,38.0,0.000000,233.690000,29.000000,130.000000,1.661180e+05,1.235669e+07,233.700000,...,15.000000,60.000000,1.00000,1.000000,233.310000,234.250000,15.000000,5.000000,1.000000,1.000000
50%,10.0,2.0,38.0,1.000000,233.800000,200.000000,130.000000,1.663280e+05,1.327258e+07,233.760000,...,100.000000,105.000000,1.00000,1.000000,233.390000,234.430000,55.000000,63.000000,1.000000,1.000000
75%,10.0,2.0,38.0,2.000000,233.920000,200.000000,130.000000,1.666125e+05,1.456848e+07,233.850000,...,110.000000,400.000000,2.00000,2.000000,233.400000,234.590000,110.000000,105.000000,2.000000,4.000000
max,10.0,2.0,38.0,9.000000,235.000000,1200.000000,130.000000,2.215188e+06,1.556924e+07,233.980000,...,1207.000000,2000.000000,3.00000,7.000000,233.660000,235.030000,1109.000000,2000.000000,3.000000,7.000000

In [83]:
# Check for missing values
df.isnull().sum()

ts_recv          0
ts_event         0
rtype            0
publisher_id     0
instrument_id    0
                ..
bid_sz_09        0
ask_sz_09        0
bid_ct_09        0
ask_ct_09        0
symbol           0
Length: 74, dtype: int64

In [ ]:
# View the columns
print(df.columns)

Index(['ts_recv', 'ts_event', 'rtype', 'publisher_id', 'instrument_id',
       'action', 'side', 'depth', 'price', 'size', 'flags', 'ts_in_delta',
       'sequence', 'bid_px_00', 'ask_px_00', 'bid_sz_00', 'ask_sz_00',
       'bid_ct_00', 'ask_ct_00', 'bid_px_01', 'ask_px_01', 'bid_sz_01',
       'ask_sz_01', 'bid_ct_01', 'ask_ct_01', 'bid_px_02', 'ask_px_02',
       'bid_sz_02', 'ask_sz_02', 'bid_ct_02', 'ask_ct_02', 'bid_px_03',
       'ask_px_03', 'bid_sz_03', 'ask_sz_03', 'bid_ct_03', 'ask_ct_03',
       'bid_px_04', 'ask_px_04', 'bid_sz_04', 'ask_sz_04', 'bid_ct_04',
       'ask_ct_04', 'bid_px_05', 'ask_px_05', 'bid_sz_05', 'ask_sz_05',
       'bid_ct_05', 'ask_ct_05', 'bid_px_06', 'ask_px_06', 'bid_sz_06',
       'ask_sz_06', 'bid_ct_06', 'ask_ct_06', 'bid_px_07', 'ask_px_07',
       'bid_sz_07', 'ask_sz_07', 'bid_ct_07', 'ask_ct_07', 'bid_px_08',
       'ask_px_08', 'bid_sz_08', 'ask_sz_08', 'bid_ct_08', 'ask_ct_08',
       'bid_px_09', 'ask_px_09', 'bid_sz_09', 'ask_sz_09', 'bid_ct_09',
       'ask_ct_09', 'symbol'],
      dtype='object')

In [74]:
class OFIFeatures:
    def __init__(self, df, levels=10):
        self.df = df.copy()
        self.levels = levels
        self.bid_sz_cols = [f'bid_sz_0{i}' for i in range(levels)]
        self.ask_sz_cols = [f'ask_sz_0{i}' for i in range(levels)]
        self.ofi_df = pd.DataFrame(index=self.df.index)

    def calculate_best_level_ofi(self):
        bid_change = self.df['bid_sz_00'].diff()
        ask_change = self.df['ask_sz_00'].diff()
        self.ofi_df['best_level_ofi'] = bid_change - ask_change
        return self.ofi_df['best_level_ofi']

    def calculate_multi_level_ofi(self):
        for i in range(self.levels):
            bid_col = self.bid_sz_cols[i]
            ask_col = self.ask_sz_cols[i]
            self.ofi_df[f'ofi_lvl_{i}'] = self.df[bid_col].diff() - self.df[ask_col].diff()
        return self.ofi_df[[f'ofi_lvl_{i}' for i in range(self.levels)]]

    def calculate_integrated_ofi(self):
        multi_level_ofi = self.calculate_multi_level_ofi().fillna(0)
        pca = PCA(n_components=1)
        integrated = pca.fit_transform(multi_level_ofi)
        self.ofi_df['integrated_ofi'] = integrated.flatten()
        return self.ofi_df['integrated_ofi']

    def calculate_cross_asset_ofi(self, time_col='ts_event', symbol_col='symbol'):
        if 'integrated_ofi' not in self.ofi_df.columns:
            self.calculate_integrated_ofi()

        combined = self.df[[symbol_col, time_col]].copy()
        combined['integrated_ofi'] = self.ofi_df['integrated_ofi']

        cross_asset_list = []
        grouped = combined.groupby(time_col)

        for ts, group in grouped:
            for sym in group[symbol_col].unique():
                other = group[group[symbol_col] != sym]
                cross_asset_list.append({
                    time_col: ts,
                    symbol_col: sym,
                    'cross_asset_ofi': other['integrated_ofi'].mean()
                })

        cross_df = pd.DataFrame(cross_asset_list)
        self.df = self.df.merge(cross_df, on=[symbol_col, time_col], how='left')
        return self.df['cross_asset_ofi']

In [75]:
# Initialise feature constructor
ofi_feature = OFIFeatures(df)

In [76]:
# Best-Level OFI
best_ofi = ofi_feature.calculate_best_level_ofi()
print("Best-Level OFI:\n", best_ofi.head(10))

Best-Level OFI:
 0      NaN
1      2.0
2      3.0
3      0.0
4      0.0
5      0.0
6      0.0
7      0.0
8    199.0
9   -199.0
Name: best_level_ofi, dtype: float64

In [77]:
# Multi-Level OFI
multi_ofi = ofi_feature.calculate_multi_level_ofi()
print("Multi-Level OFI:\n", multi_ofi.head(10))

Multi-Level OFI:
    ofi_lvl_0  ofi_lvl_1  ofi_lvl_2  ofi_lvl_3  ofi_lvl_4  ofi_lvl_5  \
0        NaN        NaN        NaN        NaN        NaN        NaN
1        2.0        0.0        0.0        0.0        0.0        0.0
2        3.0        0.0        0.0        0.0        0.0        0.0
3        0.0        0.0      200.0        0.0        0.0        0.0
4        0.0        0.0     -200.0        0.0        0.0        0.0
5        0.0      390.0     -190.0        0.0        0.0        0.0
6        0.0        0.0        0.0        0.0        0.0        0.0
7        0.0        0.0        0.0        0.0        0.0        0.0
8      199.0       -7.0     -142.0      121.0        4.0     -175.0
9     -199.0        7.0      142.0     -121.0       -4.0      175.0

   ofi_lvl_6  ofi_lvl_7  ofi_lvl_8  ofi_lvl_9
0        NaN        NaN        NaN        NaN
1        0.0        0.0        0.0        0.0
2        0.0        0.0        0.0        0.0
3        0.0        0.0        0.0        0.0
4        0.0        0.0        0.0        0.0
5        0.0        0.0        0.0        0.0
6        0.0     -156.0      111.0      245.0
7        0.0        0.0        0.0        0.0
8        0.0      156.0     -111.0     -245.0
9        0.0     -156.0      111.0      245.0

In [78]:
# Integrated OFI
integrated_ofi = ofi_feature.calculate_integrated_ofi()
print("Integrated OFI:\n", integrated_ofi.head(10))

Integrated OFI:
 0     -0.064773
1     -0.081951
2     -0.090540
3    -99.141812
4     99.012265
5    153.888006
6     -6.478507
7     -0.064773
8    104.047218
9   -104.176764
Name: integrated_ofi, dtype: float64

In [79]:
# Cross Asset OFI
cross_asset_ofi = ofi_feature.calculate_cross_asset_ofi()
print("Cross-Asset OFI:\n", cross_asset_ofi.head(10))

Cross-Asset OFI:
 0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: cross_asset_ofi, dtype: float64

In [87]:
symbol_counts = df.groupby('ts_event')['symbol'].nunique()
print(symbol_counts.value_counts())
print(df['symbol'].unique())

symbol
1    4810
Name: count, dtype: int64
['AAPL']

Cross-asset OFI cannot be calculated because the dataset contains only one symbol, AAPL, at each timestamp. Therefore there are no other assets to compare against.